### PR TITLE
Bug 1993444: cstate/pstate: Skip check on non intel arches

### PR DESCRIPTION
**Pull request by jschintag**
Backport from upstream:
https://github.com/kubernetes-sigs/node-feature-discovery/pull/570
https://github.com/kubernetes-sigs/node-feature-discovery/pull/571

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1993444

### CODE REVIEW

**Comment by kpouget** [comment]
patch looks good, it improves `detectCstate`, `detectPstate` `SelinuxEnabled` error messages by better detecting missing `sysfs`  directories vs disabled state vs incompatible drivers

**Comment by ArangoGutierrez** [comment]
Sorry the rebase took so long, PR can be found here https://github.com/openshift/node-feature-discovery/pull/52
I will personally close this PR once the rebase is in place
/hold

**Comment by jschintag** [comment]
Thank you @ArangoGutierrez

**Pull request closed without merging**
