### PR TITLE
Sync event

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
This is a Sync event patch

> The events being mirroed from upstream are specific to updating dependencies for kubernetes 1.19 and Go 1.15

here we are cherry picking the following [upstream](https://github.com/kubernetes-sigs/node-feature-discovery) commits: 

- 6172c64 
- f363ba0 
- a8c0b4a 
- 0d47a04 
- c4515b9

### CODE REVIEW

**Comment by zvonkok** [comment]
Why are we cherry-picking individual commits? Downstream should only use releases from upstream (or critical bugfixes).  Why do we need this in 4.7?

**Comment by ArangoGutierrez** [comment]
That's a good point, let's discuss it during the next scrum
/hold

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes-sigs/node-feature-discovery/issues/394

**Pull request closed without merging**
