### PR TITLE
Fix component information missing in OWNERS file

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Bugzilla component information missing for image
containers/node-feature-discovery in OCP v4.X

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
This PR is in response to AOS-ART emails asking for this line
/assign @zvonkok

**Comment by jmencak** [comment]
/lgtm
Had to do the same thing for NTO in the past.

**Review by jmencak — APPROVED** [review]
/lgtm

**Pull request merged**
