### PR TITLE
OCPBUGS-2427: update CPU flags for ARM, POWER, and Z

### PR DESCRIPTION
**Pull request by yselkowitz**
Backport of https://github.com/kubernetes-sigs/node-feature-discovery/pull/919

- cpu: update ARM CPU flags through v8.3
- cpu: update ARM CPU flags through v9.2
- cpu: add POWER10 CPU flags
- cpu: update S390 CPU flags
- cpu: document canonical sources of supported CPU flags

### CODE REVIEW

**Comment by yevgeny-shnaidman** [comment]
@yselkowitz can you just squash the commit into one, and then i will lgtm?

**Comment by yselkowitz** [comment]
@yevgeny-shnaidman squashed as requested

**Pull request merged**
