### PR TITLE
Bug  2077243: Add OPENSHIFT_VERSION label

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Review by skattoju — APPROVED** [review]
/lgtm

**Comment by skattoju** [comment]
fixes https://github.com/openshift/cluster-nfd-operator/issues/253

**Pull request merged**
